from pydantic import BaseModel, Field
from typing import Optional, List

class ClassificationResult(BaseModel):
    severity: Optional[str] = Field(description="P1, P2, P3")                     # P1, P2, P3
    affected_service: Optional[str] = Field(description=' "search-api", "billing-service"')
    incident_type: Optional[str] = Field(description='"latency", "error_rate", "availability"')
    structured_description: Optional[str] = Field(description="clean 2-3 sentence description")
    search_queries: Optional[List[str]] = Field(description="generated by classifier for search nodes")