from typing import TypedDict, List, Optional

class IncidentState(TypedDict):
    
    # ── Input ─────────────────────────────────────────────
    raw_input: str                    # whatever the user provided
    input_type: str                   # "alert", "description", "jira_id"
    
    # ── Classification ────────────────────────────────────
    severity: Optional[str]                     # P1, P2, P3
    affected_service: Optional[str]             # "search-api", "billing-service"
    incident_type: Optional[str]                # "latency", "error_rate", "availability"
    structured_description: Optional[str]       # clean 2-3 sentence description
    search_queries: Optional[List[str]]         # generated by classifier for search nodes
    
    # ── Search results ────────────────────────────────────
    knowledge_base_results: Optional[List[dict]]    # chunks + sources from RAG
    runbook_found: Optional[bool]
    runbook_title: Optional[str]
    runbook_steps: Optional[List[str]]
    similar_incidents: Optional[List[dict]]         # list of {id, description, root_cause, resolution}
    
    # ── Output ────────────────────────────────────────────
    incident_report: Optional[str]
    recommended_actions: Optional[List[str]]
    confidence_score: Optional[float]           # 0.0 to 1.0
    
    # ── Control flow ──────────────────────────────────────
    iteration_count: Optional[int]              # how many times evaluator has run
    evaluation_feedback: Optional[str]          # what the evaluator said was missing
    is_complete: Optional[bool]              # True when evaluator passes
    start_time: Optional[float]
    processing_time_seconds: Optional[float]    # track how long it took